# Generated by Django 2.1.5 on 2019-02-03 16:26

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='unique_identifier',
            field=models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False),
        ),
    ]
