# Generated by Django 2.1.5 on 2019-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190224_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/109.jpg', upload_to='profile_pics'),
        ),
    ]
