# Generated by Django 2.1.5 on 2019-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190224_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/7.jpg', upload_to='profile_pics'),
        ),
    ]
