# Generated by Django 2.1.5 on 2019-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190224_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/105.jpg', upload_to='profile_pics'),
        ),
    ]
