# Generated by Django 2.1.5 on 2019-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190224_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/250.jpg', upload_to='profile_pics'),
        ),
    ]
