# Generated by Django 2.1.5 on 2019-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190224_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/176.jpg', upload_to='profile_pics'),
        ),
    ]
