# Generated by Django 2.1.5 on 2019-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190224_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/156.jpg', upload_to='profile_pics'),
        ),
    ]
