# Generated by Django 2.1.5 on 2019-02-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_auto_20190203_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroommember',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatroomMember',
        ),
    ]
