# Generated by Django 2.1.5 on 2019-02-04 02:08

import backend.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0004_auto_20190204_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomMember',
            fields=[
                ('unique_identifier', models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('nickname', models.CharField(default='', max_length=25)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chatrooms.Chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
