# Generated by Django 2.1.5 on 2019-02-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_auto_20190218_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
    ]
