# Generated by Django 2.1.5 on 2019-02-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0004_auto_20190218_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
