# Generated by Django 2.1.5 on 2019-02-15 15:31

import backend.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatroomMembership',
            fields=[
                ('unique_identifier', models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('nickname', models.CharField(default='', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chatrooms.Chatroom')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
