# Generated by Django 2.1.5 on 2019-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom_memberships', '0002_chatroommembership_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommembership',
            options={'ordering': ['-updated_at']},
        ),
    ]
