# Generated by Django 2.1.5 on 2019-02-17 05:40

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('unique_identifier', models.CharField(default=backend.utils.id_generator, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
