# Generated by Django 2.1.5 on 2019-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190217_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/129.jpg', upload_to='profile_pics'),
        ),
    ]
