# Generated by Django 2.1.5 on 2019-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190218_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='initial_profiles/148.jpg', upload_to='profile_pics'),
        ),
    ]
